stages:
  - build

build-warden:
  stage: build
  image: golang:1.7.3
  script:
    - echo `pwd`
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    - export GOPATH=`pwd`
=======
    - mkdir -p $GOPATH/src/warden
    - mv /builds/azeroth/warden/ $GOPATH/src/warden

    - go env

    - cd $GOPATH/src/warden
>>>>>>> 1b0d98e... add ci
=======
    - mkdir -p $GOPATH/src/
    - cp -r /builds/azeroth/warden $GOPATH/src/
    - cd $GOPATH/src/warden
    - go env
>>>>>>> 22c1302... add ci; fixes #4
=======
    - mkdir -p $GOPATH/src/
    - cp -r /builds/azeroth/warden $GOPATH/src/
    - cd $GOPATH/src/warden
    - go env
>>>>>>> b2c64ec... oops mike broke it now fix CI
    - go get
    - go build
