stages:
  - build
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
  - test
  - push
  - release
>>>>>>> f3937fc... #9 first try build and push docker images in ci
=======
  # - test
=======
  - test
>>>>>>> 1714fdb...  issue #8 set up unit testing
=======
  - test
>>>>>>> 4340203... removed unused code
  # - push
  # - release
>>>>>>> 96f969d... fix ci for now

build:
  stage: build
  image: golang:1.7.3
  script:
    - echo `pwd`
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    - export GOPATH=`pwd`
=======
    - mkdir -p $GOPATH/src/warden
    - mv /builds/azeroth/warden/ $GOPATH/src/warden

    - go env

    - cd $GOPATH/src/warden
>>>>>>> 1b0d98e... add ci
=======
    - mkdir -p $GOPATH/src/
    - cp -r /builds/azeroth/warden $GOPATH/src/
    - cd $GOPATH/src/warden
    - go env
>>>>>>> 22c1302... add ci; fixes #4
=======
    - mkdir -p $GOPATH/src/
    - cp -r /builds/azeroth/warden $GOPATH/src/
    - cd $GOPATH/src/warden
    - go env
>>>>>>> b2c64ec... oops mike broke it now fix CI
    - go get
    - go build

test:
  stage: test
  image: golang:1.7.3
  script:
    - echo `pwd`
    - mkdir -p $GOPATH/src/
    - cp -r /builds/azeroth/warden $GOPATH/src/
    - cd $GOPATH/src/warden
    - go env
    - go get
    - go test ./...

# build-and-push-dev-image:
#   only:
#     - dev
#   image: docker:latest
#   services:
#     - docker:dind
#   stage: push
#   script:
#     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN 10.0.1.20:4567
#     - docker build -t 10.0.1.20:4567/azeroth/warden:dev .
#     - docker push 10.0.1.20:4567/azeroth/warden:dev
#
# build-and-push-release-image:
#   only:
#     - master
#   image: docker:latest
#   services:
#     - docker:dind
#   stage: release
#   script:
#     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN 10.0.1.20:4567
#     - docker build -t 10.0.1.20:4567/azeroth/warden:latest .
#     - docker push 10.0.1.20:4567/azeroth/warden:latest
